name: Test

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: preview
      url: https://preview.example.com
    steps:
      - run: deploy